Dependency Update, Basic JWT support and more
RocketChat/Apps.Jitsi pull request #10
Opened 2021-01-20 18:49 UTC by paulausz

# Fixes / Improvements
## Dependencies
- Updated dependencies to allow building the app using the Rocket.Chat App Engine CLI as discussed in #9 
- Added dependency for node to make is easier to build the app using the Rocket.Chat App Engine CLI

## README
- Added content to the README file to support users

## Language support
- Added German language support

# New Features
## Basic Json web token support
- Added an app setting to set a fix JWT access token as discussed in #5 
![NewSetting](https://user-images.githubusercontent.com/76944204/105219978-5fa71580-5b57-11eb-9549-629b258450a9.PNG)

# TODO
- Please verify that the app can be deployed using the Markedplace. I haven't tried that.
- Please double check the README and the English language file for typos and grammatical mistakes
- The version number has not been increased yet

# Future work
I would like to create another pull request in the upcomming days to add more settings:
- Option to create random room names for channels
- Option to create random rooms names for direct messages
- Option to set the jitsi url directly in the app

2021-01-20 18:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Apps.Jitsi?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Apps.Jitsi?pullRequest=10) before we can accept your contribution.<br/><hr/>**Paul Schmidt** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Apps.Jitsi?pullRequest=10) it.</sub>

2021-01-20 19:09 UTC, graywolf336 requested changes
Awesome, thank you for submitting this PR and these changes! Here are a few things that are mostly nitpicky 🙈

2021-01-20 19:09 UTC, graywolf336 commented on README.md
> +When authentification via JSON Web Tokens (JWT) is enabled on your Jitsi instance, you may want to add a static token for each conference link generated to allow users to enter the conference. This t
```suggestion
When authentication via JSON Web Tokens (JWT) is enabled on your Jitsi instance, you may want to add a static token for each conference link generated to allow users to enter the conference. This token can be generated here: [jwt.io](https://jwt.io/). It is recommended to set an expiration date when creating the token. The token can not be limited to a dedicated room as the same token is added to every conference link. 
```

2021-01-20 19:09 UTC, graywolf336 commented on README.md
> +## Usage
```suggestion

## Usage
```

2021-01-20 19:09 UTC, graywolf336 commented on README.md
> +## Settings
```suggestion

## Settings
```

2021-01-20 19:09 UTC, graywolf336 commented on README.md
> +### JWT Token
```suggestion

### JWT Token
```

2021-01-20 19:09 UTC, graywolf336 commented on i18n/en.json
> +    "command_description": "Generate an Jitsi video meeting URL.",
```suggestion
    "command_description": "Generate a Jitsi video meeting URL.",
```

2021-01-20 19:09 UTC, graywolf336 commented on i18n/en.json
> +    "jwt_description": "Valid JWT Token to add to all conference links. Keep empty if you do not use JWT or you do not want to append a token when creating the link!"
```suggestion
    "jwt_description": "Valid JWT Token which is added to all of the conference links. Keep it empty if you do not use JWT or you do not want to append a token when creating the link!"
```

2021-01-20 19:09 UTC, graywolf336 commented on index.ts
> +            required: true,
```suggestion
            required: false,
```

2021-01-20 21:24 UTC, paulausz commented
Thanks for your review @graywolf336. Have you also had a look at the other todos I mentioned?

2021-01-20 21:54 UTC, graywolf336 commented
No problem. I have not yet, I will be able to do those tomorrow and I'll report back to you. :)

2022-06-15 15:07 UTC, merged

2022-06-16 06:11 UTC, himpierre commented
Hi Devs.

Self created app packages throws error.

- git clone
- git checkout v2
- rc-apps create
- rc-apps package
- install via Web
- Installs but with error -> "Resource not found"

Log:
`
{"level":50,"time":"2022-06-16T06:05:07.342Z","pid":15340,"hostname":"pages","name":"Rocket.Chat Apps","msg":"Unable to access Marketplace. Does the server has access to the internet? {\"code\":428,\"requestId\":\"51b82a82-f24c-4664-8fe4-f10a9ed86ec0\",\"status\":404}"} I20220616-08:07:31.319(2) FileStream {   _readableState: ReadableState {     objectMode: false,     highWaterMark: 16384,     buffer: BufferList { head: null, tail: null, length: 0 },     length: 0,     pipes: [],     flowing: null,     ended: false,     endEmitted: false,     reading: false,     sync: true,     needReadable: false,     emittedReadable: false,     readableListening: false,     resumeScheduled: false,     errorEmitted: false,     emitClose: true,     autoDestroy: true,     destroyed: false,     errored: null,     closed: false,     closeEmitted: false,     defaultEncoding: 'utf8',     awaitDrainWriters: null,     multiAwaitDrain: false,     readingMore: false,     dataEmitted: false,     decoder: null,     encoding: null,     [Symbol(kPaused)]: null   },   _events: [Object: null prototype] {     end: [Function: bound onceWrapper] { listener: [Function (anonymous)] }   },   _eventsCount: 1,   _maxListeners: undefined,   truncated: false,   _readcb: null,   [Symbol(kCapture)]: false } {"level":50,"time":"2022-06-16T06:07:31.980Z","pid":15340,"hostname":"pages","name":"Rocket.Chat Apps","msg":"Unable to access Marketplace. Does the server has access to the internet? {\"code\":428,\"requestId\":\"03b1efe8-cb0e-478e-a677-7b7249ec482d\",\"status\":404}"} 
`

Server has for sure internet access.

cheers, t.

2022-06-16 06:27 UTC, pierre-lehnen-rc commented
I think that's an unrelated error on the rocket.chat side that doesn't prevent the app from working. 

But jitsi app v2 also relies on code that is not yet merged on rocket.chat (will be merged next week and released on version 5.0).

2022-06-16 07:14 UTC, himpierre commented
Yay!

Am 16. Juni 2022 08:28:04 MESZ schrieb Pierre Lehnen ***@***.***>:
>I think that's an unrelated error on the rocket.chat side that doesn't prevent the app from working. 
>
>But jitsi app v2 also relies on code that is not yet merged on rocket.chat (will be merged next week and released on version 5.0). 
>

2022-06-23 06:28 UTC, pierre-lehnen-rc commented
I'm implementing token generation on the app as well. Should I still keep the option to use a static token or it won't be needed anymore?